routes/admin.php
<?php

//Route::get('/home', function () {
//
////    $school=auth()->user()->name;
////
////    $path=public_path('QR/');
////    $s='ssssssssss'.'.png';
////
////
////    \QrCode::format('png')->size(500)->generate('3', $path.$s);
//    return view('admin.home');
//})->name('home');

/* Developed By Ahmed Feisal*/

Route::get('/home','HomeController@index')->name('home');
Route::resource('settings','SettingController');
Route::resource('admins','AdminController');
Route::resource('relations','RelationController');
Route::resource('defaults','DefaultController');
Route::resource('parents','ParentController');
Route::resource('children','ChildConrtoller');
Route::resource('behaviors','BehaviorController');
Route::resource('rewards','RewardController');
Route::resource('tips','TipController');
Route::delete('child_behaviors/{id}','ChildConrtoller@behavior_destroy')->name('child_behaviors.destroy');
Route::delete('child_rewards/{id}','ChildConrtoller@reward_destroy')->name('child_rewards.destroy');
Route::get('child_set/{id}','ChildConrtoller@set_password')->name('children.set_password');

Route::get('send/notification',function(){
    return view('admin.notification.index');
})->name('notification.create');

Route::post('notification','NotificationController@notification')->name('notification.store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Developed By Ahmed Feisal*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([/*'prefix' => 'admin'*/], function () {
    Route::get('/', function () {
        return redirect(route('adminlogin'));
    });
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('adminlogin');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('adminlogout');
//    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('adminregister');
//    Route::post('/register', 'AdminAuth\RegisterController@register');
    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('adminpassword.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('adminpassword.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('adminpassword.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

resources/views/admin/admins/_form.blade.php
<div class="form-body">
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('name') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('name',old('name'),['class'=>'form-control'])!!}
        <label for="form_control_1">إسم العضو</label>
    </div>

    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('email') ? ' has-error' : 'has-success' }}">

        {!!Form::text('email',old('email'),['class'=>'form-control'])!!}
        <label for="form_control_1">البريد الالكترونى</label>
    </div>


    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('password') ? ' has-error' : 'has-success' }}">
        {!!Form::password('password',['class'=>'form-control'])!!}
        <label for="form_control_1">كلمه المرور</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('password_confirmation') ? ' has-error' : 'has-success' }}">
        {!!Form::password('password_confirmation',['class'=>'form-control'])!!}
        <label for="form_control_1">تأكيد كلمه المرور</label>
    </div>

    <div class="form-group form-md-line-input form-md-floating-label{{ $errors->has('image') ? ' has-error' : 'has-success' }}">
        @if(isset($Admin))
            <img src="{!! asset($Admin->image) !!}" width="100px">
        @endif
        {!!Form::file('image',['class'=>'form-control'])!!}
        <label for="form_control_1">الصوره</label>
    </div>

</div>
<div class="form-actions noborder">
    <button type="submit" class="btn blue btn_1">حفظ</button>
    <button type="reset" class="btn default btn_2">الغاء</button>
</div>

resources/views/admin/admins/_table.blade.php
<table class="table table-striped table-bordered table-hover dt-responsive display example" width="100%"
       id="sample_3" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="all  text-center">#</th>
        <th class="all  text-center">الصورة</th>
        <th class="all  text-center">الاسم</th>
        <th class="min-phone-l  text-center">الايميل</th>


        <th class="min-tablet text-center">الاعدادت</th>

    </tr>
    </thead>
    <tbody>
    @foreach($Admins as $Admin)
        <tr>
            <td class="text-center">{!!$loop->iteration!!}</td>
            <td><img src="{!! asset($Admin->image) !!}" width="100px" ></td>
            <td>{!!$Admin->name!!}</td>
            <td>{!!$Admin->email!!}</td>
            {!!Form::open( ['route' => ['admins.destroy',$Admin->id] ,'id'=>'delete-form'.$Admin->id, 'method' => 'Delete']) !!}
            {!!Form::close() !!}
            <td colspan="1">
                <div class="margin-bottom-5">
                    <a href="{{route('admins.edit',[$Admin->id])}}"
                       class="btn btn-sm green btn-outline filter-submit margin-bottom">
                        <i class="fa fa-pencil-square"></i> تعديل </a>
                </div>

                <div class="margin-bottom-5">
                    <a onclick="Delete({{$Admin->id}})" href="#"
                       class="btn btn-sm text-danger btn-outline filter-submit margin-bottom">
                        <i class="fa fa-trash"></i> حذف</a>
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.app')
@section('title')اضافه مدير جديد@endsection
@section('header')@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-pin font-green"></i>
                        <span class="caption-subject bold uppercase"> اضافه مدير جديد</span>
                    </div>

                </div>
                <div class="portlet-body form">

                    <form role="form" action="{{ route('admins.store') }}"  method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        @include('admin.admins._form')
                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection
@section('footer')

@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')
@section('title')تعديل بيانات مدير {{$Admin->name}}@endsection
@section('header')@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-pin font-green"></i>
                        <span class="caption-subject bold uppercase"> تعديل بيانات مدير {{$Admin->name}}</span>
                    </div>

                </div>
                <div class="portlet-body form">

                    {!!Form::model($Admin,['route'=>['admins.update',$Admin->id],'method'=>'put', 'novalidate','files'=>'true'])!!}
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @include('admin.admins._form')
                    {!! Form::close() !!}
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection
@section('footer')


@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')
@section('title')المديرين @endsection
@section('header')@endsection
@section('content')

    <div class="page-head">
        <div class="page-title">
            <h1 class="text-center">المديرين<hr></h1>
        </div>
    </div>

    <!-- Start Code Table Studeصnt-->
    <section class="Table">
        <div class="row">
            @include('admin.admins._table')
        </div>
    </section>
    <!-- eND Code Table Student-->



@endsection
@section('footer')
    <script>
        function Delete(id) {
            var item_id=id;
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا المدير ؟",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم الإلغاء", "حذف المدير تم الغاؤه", "error");
                }
            });
        };
    </script>
@stop