routes/admin.php
<?php

//Route::get('/home', function () {
//
////    $school=auth()->user()->name;
////
////    $path=public_path('QR/');
////    $s='ssssssssss'.'.png';
////
////
////    \QrCode::format('png')->size(500)->generate('3', $path.$s);
//    return view('admin.home');
//})->name('home');

/* Developed By Ahmed Feisal*/

Route::get('/home','HomeController@index')->name('home');
Route::resource('settings','SettingController');
Route::resource('admins','AdminController');
Route::resource('relations','RelationController');
Route::resource('defaults','DefaultController');
Route::resource('parents','ParentController');
Route::resource('children','ChildConrtoller');
Route::resource('behaviors','BehaviorController');
Route::resource('rewards','RewardController');
Route::resource('tips','TipController');
Route::delete('child_behaviors/{id}','ChildConrtoller@behavior_destroy')->name('child_behaviors.destroy');
Route::delete('child_rewards/{id}','ChildConrtoller@reward_destroy')->name('child_rewards.destroy');
Route::get('child_set/{id}','ChildConrtoller@set_password')->name('children.set_password');

Route::get('send/notification',function(){
    return view('admin.notification.index');
})->name('notification.create');

Route::post('notification','NotificationController@notification')->name('notification.store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Developed By Ahmed Feisal*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group([/*'prefix' => 'admin'*/], function () {
    Route::get('/', function () {
        return redirect(route('adminlogin'));
    });
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('adminlogin');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('adminlogout');
//    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('adminregister');
//    Route::post('/register', 'AdminAuth\RegisterController@register');
    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('adminpassword.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('adminpassword.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('adminpassword.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

app/Models/Behavior.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Behavior extends Model
{
    protected $table='behaviors';
    protected $fillable = ['type','title','user_id','points'];

    public function scopefindByType($query, $type)
    {
        return $query->where('type', $type)->get();
    }

    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Http/Controllers/Admin/BehaviorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Behavior;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Laracasts\Flash\Flash;

class BehaviorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $defaults=Behavior::all();

        return view('admin.behaviors.index',compact('defaults'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.behaviors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requests = $request->except('_token');
        $coun=Behavior::create($requests);
        if (!$coun){
            Flash::error('حدث خطأ أثناء التسجيل');

            return back();
        }
        Flash::success('تم التسجيل بنجاح');

        return redirect(route('behaviors.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $behavior=Behavior::find($id);
        if(is_null($behavior)){
            Flash::error('هذا المحتوي غير موجود');
            return back();
        }
        return view('admin.behaviors.edit',compact('behavior'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $default=Behavior::find($id);
        if(is_null($default)){
            Flash::error('هذا المحتوي غير موجود');
            return back();
        }

        $requests = $request->except('_token');

        $default->update($requests);
        Flash::success('تم التعديل بنجاح');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $default=Behavior::find($id);
        if(is_null($default)){
            Flash::error('هذا المحتوي غير موجود');
            return back();
        }
        $default->delete();
        Flash::success('تم الحذف بنجاح');

        return back();
    }
}

resources/views/admin/behaviors/_form.blade.php
<div class="form-body">
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('user_id') ? ' has-error' : 'has-success' }} ">
        {!!Form::select('user_id',parents(),old('user_id'),['class'=>'form-control','required'=>'required'])!!}
        <label for="form_control_1">ولي الأمر</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('title') ? ' has-error' : 'has-success' }} ">
        {!!Form::text('title',old('title'),['class'=>'form-control','required'=>'required'])!!}
        <label for="form_control_1">الاسم </label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('points') ? ' has-error' : 'has-success' }} ">
        {!!Form::number('points',old('points'),['class'=>'form-control','required'=>'required'])!!}
        <label for="form_control_1">النقاط</label>
    </div>
    <div class="form-group form-md-line-input form-md-floating-label  {{ $errors->has('type') ? ' has-error' : 'has-success' }} ">
        {!!Form::select('type',['good'=>'جيد','bad'=>'سيئ'],old('type'),['class'=>'form-control','required'=>'required'])!!}
        <label for="form_control_1">النوع</label>
    </div>

</div>
<div class="form-actions noborder">
    <button type="submit" class="btn blue btn_1">حفظ</button>
    <button type="reset" class="btn default btn_2">الغاء</button>
</div>

resources/views/admin/behaviors/_table.blade.php
<table class="table datatable-button-init-basic display example">
    <thead>
    <tr>
        <th> # </th>
        <th> الاسم  </th>
        <th> النقاط </th>
        <th> النوع </th>
        <th> ولي الامر </th>
        <th> العمليات </th>
    </tr>
    </thead>
    <tbody>
    @foreach($defaults as $key)
        <tr>
            <td>{!!$loop->iteration!!}</td>
            <td>{{$key->title}}</td>
            <td>{{$key->type=='good'?$key->points:'-'.$key->points}}</td>
            <td>{{$key->type=='good'?'جيد':'سيئ'}}</td>
            <td><a href="{{route('parents.show',[$key->user->id])}}">{{$key->user->name}}</a></td>
            {!!Form::open( ['route' => ['behaviors.destroy',$key->id] ,'id'=>'delete-form'.$key->id, 'method' => 'Delete']) !!}
            {!!Form::close() !!}
            <td>
                <div class="margin-bottom-5">
                    <a onclick="Delete({{$key->id}})" href="#"
                       class="btn btn-sm text-danger btn-outline filter-submit margin-bottom">
                        <i class="fa fa-trash"></i> حذف</a>
                </div>

                <div class="margin-bottom-5">
                    <a href="{{route('behaviors.edit',['id'=>$key->id])}}"
                       class="btn btn-sm green btn-outline filter-submit margin-bottom">
                        <i class="fa fa-pencil-square"></i> تعديل</a>
                </div>

            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/behaviors/create.blade.php
@extends('admin.layouts.app')
@section('title')اضافه سلوك  جديد@endsection
@section('header')@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-pin font-green"></i>
                        <span class="caption-subject bold uppercase"> اضافه سلوك  جديد</span>
                    </div>

                </div>
                <div class="portlet-body form">

                    <form role="form" action="{{ route('behaviors.store') }}"  method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        @include('admin.behaviors._form')
                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection
@section('footer')

@endsection

resources/views/admin/behaviors/edit.blade.php
@extends('admin.layouts.app')
@section('title')تعديل بيانات  {{$behavior->title}}@endsection
@section('header')@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green">
                        <i class="icon-pin font-green"></i>
                        <span class="caption-subject bold uppercase">تعديل بيانات  {{$behavior->title}}</span>
                    </div>

                </div>
                <div class="portlet-body form">

                    {!!Form::model($behavior,['route'=>['behaviors.update',$behavior->id],'method'=>'put', 'novalidate','files'=>'true'])!!}
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @include('admin.behaviors._form')
                    {{Form::close()}}
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
            <!-- BEGIN SAMPLE FORM PORTLET-->

            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection
@section('footer')


@endsection

resources/views/admin/behaviors/index.blade.php
@extends('admin.layouts.app')
@section('title')السلوكيات @endsection
@section('header')@endsection
@section('content')

    <div class="page-head">
        <div class="page-title">
            <h1 class="text-center">السلوكيات <hr></h1>
        </div>
    </div>

    <!-- Start Code Table Studeصnt-->
    <section class="Table">
        <div class="row">
            @include('admin.behaviors._table')
        </div>
    </section>
    <!-- eND Code Table Student-->



@endsection
@section('footer')
    <script>
        function Delete(id) {
            var item_id=id;
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذالسلوك ؟",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم الإلغاء", "حذف السلوك تم الغاؤه", "error");
                }
            });
        };
    </script>
@stop